// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package HelloService

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HServiceClient is the client API for HService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HServiceClient interface {
	// Sends a greeting
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error)
}

type hServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHServiceClient(cc grpc.ClientConnInterface) HServiceClient {
	return &hServiceClient{cc}
}

func (c *hServiceClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloReply, error) {
	out := new(HelloReply)
	err := c.cc.Invoke(ctx, "/HService/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HServiceServer is the server API for HService service.
// All implementations must embed UnimplementedHServiceServer
// for forward compatibility
type HServiceServer interface {
	// Sends a greeting
	SayHello(context.Context, *HelloRequest) (*HelloReply, error)
	mustEmbedUnimplementedHServiceServer()
}

// UnimplementedHServiceServer must be embedded to have forward compatible implementations.
type UnimplementedHServiceServer struct {
}

func (UnimplementedHServiceServer) SayHello(context.Context, *HelloRequest) (*HelloReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedHServiceServer) mustEmbedUnimplementedHServiceServer() {}

// UnsafeHServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HServiceServer will
// result in compilation errors.
type UnsafeHServiceServer interface {
	mustEmbedUnimplementedHServiceServer()
}

func RegisterHServiceServer(s grpc.ServiceRegistrar, srv HServiceServer) {
	s.RegisterService(&HService_ServiceDesc, srv)
}

func _HService_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HServiceServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/HService/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HServiceServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HService_ServiceDesc is the grpc.ServiceDesc for HService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "HService",
	HandlerType: (*HServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _HService_SayHello_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "com/rams/proto/HelloService.proto",
}
